name: Ollama container example
on: workflow_dispatch

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        volumes:
          - ollama_data:/root/.ollama

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for Ollama
        run: |
          echo "Waiting for Ollama to be ready..."
          for i in {1..10}; do
            curl -f http://localhost:11434 && break
            echo "Ollama not ready yet... retrying"
            sleep 5
          done

      - name: Run tests
        run: |
          echo "Running tests..."
          python test.py
