name: Ollama container example
on: workflow_dispatch

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16-bullseye

    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - "11434:11434"
        volumes:
          - ollama_data:/root/.ollama

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Ollama service
        run: |
          echo "Testing Ollama service..."
          curl -s http://localhost:11434 || exit 1