name: Update Available Models

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub App Token
        id: get_app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Python script
        run: python src/get_models.py

      - name: Commit and push changes
        run: |
            git config --global user.name 'MandelAuto-App'
            git config --global user.email 'MandelAuto-App@users.noreply.github.com'
            git add AVAILABLE_MODELS.md
            git commit -m 'Update AVAILABLE_MODELS.md' || echo "No changes to commit"
            git push
        env:
            GITHUB_TOKEN: ${{ steps.get_app_token.outputs.token }}
